apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-plugins-root
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # Skip health check - PVC stays Pending until consumed (WaitForFirstConsumer)
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
