---
apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-operator
  labels:
    name: rhdh-operator
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhdh-operator-operatorgroup
  namespace: rhdh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh
  namespace: rhdh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: fast
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
